# -*- coding: utf-8 -*-
"""predict_gdp_5yr_with_groups.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WQ0u7Rk_y_DBjN1lFQPm11CPIF2yqBjk
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression


START_YEAR = 1960
END_YEAR = 2022
GDP_FILE = "/content/drive/MyDrive/gdp_pcap.csv"
CO2_FILE = "/content/drive/MyDrive/co2_pcap_cons.csv"
OUTPUT_FILE = "merged_co2_gdp.csv"


# Step 1: Load, reshape, merge, and clean the data

def load_and_clean_data(gdp_file: str = GDP_FILE, co2_file: str = CO2_FILE) -> pd.DataFrame:
    gdp = pd.read_csv(gdp_file)
    co2 = pd.read_csv(co2_file)

    gdp_long = gdp.melt(
        id_vars=["geo", "name"],
        var_name="year",
        value_name="gdp_per_capita"
    )

    co2_long = co2.melt(
        id_vars=["geo", "name"],
        var_name="year",
        value_name="co2_per_capita"
    )

    gdp_long["year"] = pd.to_numeric(gdp_long["year"], errors="coerce")
    co2_long["year"] = pd.to_numeric(co2_long["year"], errors="coerce")

    gdp_long = gdp_long.dropna(subset=["year"])
    co2_long = co2_long.dropna(subset=["year"])

    gdp_long["year"] = gdp_long["year"].astype(int)
    co2_long["year"] = co2_long["year"].astype(int)

    gdp_long = gdp_long[(gdp_long["year"] >= START_YEAR) & (gdp_long["year"] <= END_YEAR)]
    co2_long = co2_long[(co2_long["year"] >= START_YEAR) & (co2_long["year"] <= END_YEAR)]

    df = gdp_long.merge(
        co2_long,
        on=["geo", "name", "year"],
        how="inner"
    )

    df["gdp_per_capita"] = pd.to_numeric(df["gdp_per_capita"], errors="coerce")
    df["co2_per_capita"] = pd.to_numeric(df["co2_per_capita"], errors="coerce")

    df = df.dropna(subset=["gdp_per_capita", "co2_per_capita"])
    df = df[df["gdp_per_capita"] > 0].copy()

    df["log_gdp"] = np.log(df["gdp_per_capita"])
    df = df.sort_values(["geo", "year"])
    df["co2_lag1"] = df.groupby("geo")["co2_per_capita"].shift(1)

    return df


# Step 2: Use the lag variable in a visualization

def plot_lagged_co2_vs_gdp(df: pd.DataFrame) -> None:
    plot_df = df.dropna(subset=["co2_lag1", "gdp_per_capita"])

    plt.figure(figsize=(8, 6))
    plt.scatter(plot_df["co2_lag1"], plot_df["gdp_per_capita"], alpha=0.3)
    plt.xlabel("CO2 per capita (lagged by 1 year)")
    plt.ylabel("GDP per capita")
    plt.title("Lagged CO2 Emissions vs GDP per Capita")
    plt.tight_layout()
    plt.show()


# Step 3: Add a better visualization using log GDP

def plot_co2_vs_log_gdp(df: pd.DataFrame) -> None:
    plot_df = df.dropna(subset=["co2_per_capita", "log_gdp"])

    plt.figure(figsize=(8, 6))
    plt.scatter(plot_df["co2_per_capita"], plot_df["log_gdp"], alpha=0.3)
    plt.xlabel("CO2 per capita")
    plt.ylabel("Log GDP per capita")
    plt.title("CO2 Emissions vs Log GDP per Capita")
    plt.tight_layout()
    plt.show()


# Step 4: Correlation analysis

def print_correlations(df: pd.DataFrame) -> None:
    corr_df = df[["log_gdp", "co2_per_capita", "co2_lag1"]].dropna()
    corr_matrix = corr_df.corr()

    print("\nCorrelation matrix:")
    print(corr_matrix)


# Step 5: Regression using lagged CO2 to predict log GDP

def run_regression(df: pd.DataFrame) -> None:
    reg_df = df[["co2_lag1", "log_gdp"]].dropna()

    X = reg_df[["co2_lag1"]]
    y = reg_df["log_gdp"]

    model = LinearRegression()
    model.fit(X, y)

    print("\nLinear regression results:")
    print(f"Coefficient: {model.coef_[0]:.6f}")
    print(f"Intercept: {model.intercept_:.6f}")
    print(f"R^2: {model.score(X, y):.6f}")


# Optional: save cleaned merged dataset for later use

def save_processed_data(df: pd.DataFrame, output_file: str = OUTPUT_FILE) -> None:
    df.to_csv(output_file, index=False)
    print(f"\nProcessed dataset saved to: {output_file}")


if __name__ == "__main__":
    df = load_and_clean_data()

    print("First 5 rows:")
    print(df.head())

    print(f"\nDataset shape: {df.shape}")
    print("\nMissing values:")
    print(df[["gdp_per_capita", "co2_per_capita", "log_gdp", "co2_lag1"]].isna().sum())

    save_processed_data(df)
    plot_lagged_co2_vs_gdp(df)
    plot_co2_vs_log_gdp(df)
    print_correlations(df)
    run_regression(df)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error


df = pd.read_csv("merged_co2_gdp.csv")


# STEP 1: Create 5-year future GDP target

df = df.sort_values(["geo", "year"])

df["gdp_5yr_ahead"] = df.groupby("geo")["gdp_per_capita"].shift(-5)
df["log_gdp_5yr_ahead"] = np.log(df["gdp_5yr_ahead"])

# Drop missing values (important!)
df = df.dropna(subset=["log_gdp", "co2_lag1", "log_gdp_5yr_ahead"])

# STEP 2: Define features & target

X = df[["log_gdp", "co2_lag1"]]   # current GDP + lagged CO2
y = df["log_gdp_5yr_ahead"]

# Train/test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# STEP 3: Train regression model

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

# Evaluation
r2 = model.score(X_test, y_test)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print("=== 5-Year GDP Prediction Model ===")
print(f"R^2: {r2:.4f}")
print(f"RMSE: {rmse:.4f}")
print("Coefficients:", dict(zip(X.columns, model.coef_)))

# STEP 4: Prediction visualization

plt.scatter(y_test, y_pred, alpha=0.3)
plt.xlabel("Actual Log GDP (5 years ahead)")
plt.ylabel("Predicted Log GDP")
plt.title("Prediction vs Actual (5-Year GDP)")
plt.show()


# STEP 5: Country grouping
# Create GDP-based groups (low / medium / high income proxy)
df["gdp_group"] = pd.qcut(df["gdp_per_capita"], 3, labels=["Low", "Middle", "High"])

# Compare relationship by group
groups = df["gdp_group"].unique()

for group in groups:
    subset = df[df["gdp_group"] == group]

    plt.scatter(
        subset["co2_per_capita"],
        subset["gdp_per_capita"],
        alpha=0.3,
        label=group
    )

plt.xlabel("CO2 per capita")
plt.ylabel("GDP per capita")
plt.title("CO2 vs GDP by Income Group")
plt.legend()
plt.show()

# -----------------------------
# STEP 6: Compare model performance by group
# -----------------------------
print("\n=== Model Performance by GDP Group ===")

for group in groups:
    subset = df[df["gdp_group"] == group]

    subset = subset.dropna(subset=["log_gdp", "co2_lag1", "log_gdp_5yr_ahead"])

    if len(subset) < 50:
        continue  # skip small groups

    X_sub = subset[["log_gdp", "co2_lag1"]]
    y_sub = subset["log_gdp_5yr_ahead"]

    X_train, X_test, y_train, y_test = train_test_split(
        X_sub, y_sub, test_size=0.2, random_state=42
    )

    model = LinearRegression()
    model.fit(X_train, y_train)

    r2 = model.score(X_test, y_test)

    print(f"{group} countries → R^2: {r2:.4f}")